[package]
name = "bevy-portals"
version = "0.1.0"
edition = "2021"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = 3

[features]
default = ["debug"]
debug = ["bevy/dynamic_linking", "dep:bevy_editor_pls"]

[dependencies]
bevy = { version = "0.13.2" }
bevy_editor_pls = { version = "0.8.1", optional = true }
bevy_rapier3d = { version = "0.26.0", features = ["parallel", "simd-stable"] }
uom = "0.36.0"
